sklep/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from sklep.models import Towary, Klienci
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import password_reset

urlpatterns = patterns('',
    url(r'^produkty/$', 'django.views.generic.list_detail.object_list', {'queryset': Towary.objects.filter(ilosc_w_sklepie__gt=0).select_related('kategorie').order_by('nazwa_towaru'), 'paginate_by': 8}, "sklep_produkty"),
    url(r'^produkty/rosnacacena/$', 'django.views.generic.list_detail.object_list', {'queryset': Towary.objects.filter(ilosc_w_sklepie__gt=0).select_related('kategorie').order_by('cena_sklepowa'), 'paginate_by': 8}, "sklep_produkty_rosnace"),
    url(r'^produkty/malejacacena/$', 'django.views.generic.list_detail.object_list', {'queryset': Towary.objects.filter(ilosc_w_sklepie__gt=0).select_related('kategorie').order_by('-cena_sklepowa'), 'paginate_by': 8}, "sklep_produkty_malejace"),
    url(r'^produkty/rosnacanazwa/$', 'django.views.generic.list_detail.object_list', {'queryset': Towary.objects.filter(ilosc_w_sklepie__gt=0).select_related('kategorie').order_by('nazwa_towaru'), 'paginate_by': 8}, "sklep_produkty_rosnacenazwa"),
    url(r'^produkty/malejacanazwa/$', 'django.views.generic.list_detail.object_list', {'queryset': Towary.objects.filter(ilosc_w_sklepie__gt=0).select_related('kategorie').order_by('-nazwa_towaru'), 'paginate_by': 8}, "sklep_produkty_malejacenazwa"),
    url(r'^kontakt/$', 'sklep.views.strona_kontakt', name="sklep_kontakt"),
    url(r'^index/$', 'sklep.views.koszyk', name="sklep_koszyk"),
    url(r'^menage/$', 'sklep.views.manage_articles', name="sklep_manage_articles"),
    url(r'^koszyk/$', 'sklep.views.koszykobsluga', name="koszykobsluga"),
    url(r'^finalizacja/$', 'sklep.views.finalizacja', name="finalizacja"),
    url(r'^regulamin/$', 'sklep.views.regulamin', name="regulamin"),
    url(r'^klient/(\d+)/$', 'sklep.views.zmien_klienta', name="zmien_klienta"),
    url(r'^klient/$', 'sklep.views.dodaj_klienta', name="dodaj_klienta"),
    url(r'^rejestracja/$', 'sklep.views.register', name="sklep_register"),
    url(r'^logowanie/$', 'django.contrib.auth.views.login', {'template_name': 'registration/login.html'}),
    url(r'^koszyk/dodaj/(\d+)/$', 'sklep.views.koszyk_dodaj', name="sklep_koszyk_dodaj"),
    url(r'^koszyk/usun/(\d+)/$', 'sklep.views.koszyk_usun', name="sklep_koszyk_usun"),
    url(r'^koszyk/usun/$', 'sklep.views.koszyk_usunwszystko', name="sklep_koszyk_usunwszystko"),
    url(r'^produkty/(\d+)/$', 'sklep.views.produkty_z_kategorii', name="sklep_kategoria"),
    url(r'^produkty/(\d+)/rosnacacena/$', 'sklep.views.produkty_z_kategoriirosnace', name="sklep_kategoria_rosnace"),
    url(r'^produkty/(\d+)/malejacacena/$', 'sklep.views.produkty_z_kategoriimalejace', name="sklep_kategoria_malejace"),
    url(r'^produkty/(\d+)/rosnacanazwa/$', 'sklep.views.produkty_z_kategoriirosnacenazwa', name="sklep_kategoria_rosnacenazwa"),
    url(r'^produkty/(\d+)/malejacanazwa/$', 'sklep.views.produkty_z_kategoriimalejacenazwa', name="sklep_kategoria_malejacenazwa"),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/sklep/'} ),
    url(r'^search/', include('haystack.urls')),
    url(r'^password_change/$', 'sklep.views.password_change', {'template_name': 'registration/password_change_form1.html','post_change_redirect' : '/sklep/password_change/done/'}),
    url(r'^password_change/done/$', 'sklep.views.password_change_done', {'template_name': 'registration/password_change_done1.html'}),
    url(r'^password/reset/$', 'sklep.views.password_reset', {'template_name': 'registration/password_reset_form1.html','post_reset_redirect' : '/sklep/password/reset/done/'}),
    url(r'^password/reset/done/$', 'sklep.views.password_reset_done', {'template_name': 'registration/password_reset_done1.html'}),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name': 'registration/password_reset_confirm1.html','post_reset_redirect' : '/sklep/password/done/'}),
    url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete',{'template_name': 'registration/password_reset_complete1.html'}),
    url(r'^setlang/(?P<lang_code>.*)/$', 'sklep.views.set_language'),
    url(r'', 'sklep.views.strona_glowna', name="sklep_glowna"),

    )

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',url(r'^sklep/', include('sklep.urls')),
    # Examples:
    # url(r'^$', 'zpi.views.home', name='home'),
    # url(r'^zpi/', include('zpi.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
url(r'^admin/', include(admin.site.urls)),
	(r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

sklep/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models
import datetime
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.db.models.signals import post_save
from django.contrib.localflavor.pl.forms import PLPostalCodeField

class Klienci(models.Model):
    nik = models.BigIntegerField(primary_key=True, null=True, blank=True)
    nip = models.CharField(max_length=11, unique=True, blank=True, null=True)
    nazwa_firmy = models.CharField(max_length=50)
    nazwisko = models.CharField(max_length=30)
    imie = models.CharField(max_length=30)
    miasto = models.CharField(max_length=30)
    ulica = models.CharField(max_length=40, blank=True)
    numer = models.CharField(max_length=7)
    kod_pocztowy = models.CharField(max_length=6)
    poczta = models.CharField(max_length=30)
    telefon = models.CharField(max_length=13, blank=True, null=True)
    login = models.ForeignKey(User, unique=True, max_length=20, null=True, blank=True)
    class Meta:
		verbose_name='Klient'
		db_table = u'klienci'
		verbose_name_plural = 'Klienci'
		ordering = ('nik',)

    def __unicode__(self):
        return self.nazwisko


class Stanowiska(models.Model):
    identyfikator = models.BigIntegerField(primary_key=True)
    stanowisko = models.CharField(max_length=50, unique=True)
    class Meta:
		verbose_name='Stanowisko'
		db_table = u'stanowiska'
		verbose_name_plural = 'Stanowiska'
		ordering = ('identyfikator',)

    def __unicode__(self):
        return self.stanowisko

class Dostawcy(models.Model):
    nid = models.BigIntegerField(primary_key=True)
    regon = models.BigIntegerField(unique=True, null=True, blank=True)
    nip = models.CharField(max_length=11, unique=True)
    nazwa_dostawcy = models.CharField(max_length=30)
    miasto = models.CharField(max_length=30)
    ulica = models.CharField(max_length=40, blank=True)
    numer = models.CharField(max_length=7)
    kod_pocztowy = models.CharField(max_length=6)
    poczta = models.CharField(max_length=30)
    telefon = models.CharField(max_length=13, blank=True)
    class Meta:
		verbose_name='Dostawca'
		db_table = u'dostawcy'
		verbose_name_plural = 'Dostawcy'
		ordering = ('nid',)

    def __unicode__(self):
        return self.nazwa_dostawcy


class Pracownicy(models.Model):
    np = models.BigIntegerField(primary_key=True)
    nazwisko = models.CharField(max_length=30)
    imie = models.CharField(max_length=30)
    pesel = models.CharField(max_length=15, unique=True)
    nip = models.CharField(max_length=11, unique=True)
    miasto = models.CharField(max_length=30)
    ulica = models.CharField(max_length=40, blank=True)
    numer = models.CharField(max_length=7)
    kod_pocztowy = models.CharField(max_length=6)
    poczta = models.CharField(max_length=30)
    stanowisko = models.ForeignKey(Stanowiska, null=True, db_column='stanowisko', blank=True)
    class Meta:
		verbose_name='Pracownik'
		db_table = u'pracownicy'
		verbose_name_plural = 'Pracownicy'
		ordering = ('np',)

    def __unicode__(self):
        return self.nazwisko

class Hasla(models.Model):
    identyfikator = models.ForeignKey(Pracownicy, unique=True, db_column='identyfikator')
    login = models.CharField(max_length=50, unique=True)
    haslo = models.CharField(max_length=20)
    class Meta:
		verbose_name='Haslo'
		db_table = u'hasla'
		verbose_name_plural = 'Hasla'
		ordering = ('identyfikator',)

    def __unicode__(self):
        return self.login

class Kategorie(models.Model):
    identyfikator = models.BigIntegerField(primary_key=True)
    nazwa = models.CharField(max_length=30, unique=True)
    class Meta:
		verbose_name='Kategoria'
		db_table = u'kategorie'
		verbose_name_plural = 'Kategorie'
		ordering = ('identyfikator',)

    def __unicode__(self):
        return self.nazwa	
	
	#@permalink
	#def get_absolute_url(self):
	#	return ('sklep_kategoria', (self.pk,)) 
	
    def get_absolute_url(self):
        return reverse('sklep_kategoria', args=[self.pk,])

class Towary(models.Model):
    idtowaru = models.BigIntegerField(primary_key=True)
    nazwa_towaru = models.CharField(max_length=255, unique=True)
    ilosc_w_sklepie = models.BigIntegerField()
    cena_sklepowa = models.DecimalField(max_digits=126, decimal_places=2)
    minimum_towar = models.BigIntegerField()
    opis = models.CharField(max_length=1000, blank=True)
    zdjecie = models.CharField(max_length=255, blank=True)
    kategoria = models.ForeignKey(Kategorie, db_column='kategoria')
    class Meta:
		verbose_name='Towar'
		db_table = u'towary'
		verbose_name_plural = 'Towary'
		ordering = ('idtowaru',)

    def __unicode__(self):
        return self.nazwa_towaru

class Dostawy(models.Model):
    iddostawy = models.BigIntegerField(primary_key=True)
    nid = models.ForeignKey(Dostawcy, db_column='nid')
    data_dostawy = models.DateField()
    status = models.CharField(max_length=20)
    np = models.ForeignKey(Pracownicy, db_column='np')
    class Meta:
		verbose_name='Dostawa'
		db_table = u'dostawy'
		verbose_name_plural = 'Dostawy'
		ordering = ('iddostawy',)


class OpisyDostaw(models.Model):
    iddostawy = models.ForeignKey(Dostawy, unique=True, db_column='iddostawy')
    idtowaru = models.ForeignKey(Towary, unique=True, db_column='idtowaru')
    ilosc = models.BigIntegerField()
    cena_producenta = models.DecimalField(max_digits=126, decimal_places=2)
    class Meta:
		verbose_name='Opis dostawy'
		db_table = u'opisy_dostaw'
		verbose_name_plural = 'Opisy dostaw'
		ordering = ('iddostawy','idtowaru',)
		
class Wysylka(models.Model):
    identyfikator = models.BigIntegerField(primary_key=True)
    rodzaj = models.CharField(max_length=100, unique=True, blank=True)
    cena = models.DecimalField(max_digits=126, decimal_places=2)
    class Meta:
		verbose_name='Wysylka'
		db_table = u'wysylka'
		verbose_name_plural = 'Wysylki'
		ordering = ('identyfikator',)

    def __unicode__(self):
        return self.rodzaj+ ' : ' + unicode(self.cena) + ' zl'
		
class Zamowienia(models.Model):
    idzamowienia = models.BigIntegerField(primary_key=True, null=True, blank=True)
    nik = models.ForeignKey(Klienci, null=True, db_column='nik', blank=True)
    np = models.ForeignKey(Pracownicy, null=True, db_column='np', blank=True)
    data_zamowienia = models.DateField(blank=True)
    status = models.CharField(max_length=20, null=True, blank=True)
    wysylka = models.ForeignKey(Wysylka, db_column='wysylka')
    class Meta:
		verbose_name='Zamowienie'
		db_table = u'zamowienia'
		verbose_name_plural = 'Zamowienia'
		ordering = ('idzamowienia',)
		
    def __unicode__(self):
        return unicode(self.idzamowienia)

class OpisyZamowien(models.Model):
    ident = models.BigIntegerField(primary_key=True, null=True, blank=True)
    idzamowienia1 = models.ForeignKey(Zamowienia, db_column='idzamowienia1', null=True, blank=True)
    idtowaru = models.ForeignKey(Towary, db_column='idtowaru', null=True, blank=True)
    ilosc = models.BigIntegerField()
    class Meta:
		verbose_name='Opis zamowienia'
		db_table = u'opisy_zamowien'
		verbose_name_plural = 'Opisy zamowien'
		ordering = ('idzamowienia1','idtowaru',)

class Ksiegowosc(models.Model):
    idtransakcji = models.BigIntegerField(primary_key=True)
    kwota = models.DecimalField(null=True, max_digits=126, decimal_places=2, blank=True)
    idzamowienia = models.ForeignKey(Zamowienia, null=True, db_column='idzamowienia', blank=True)
    iddostawy = models.ForeignKey(Dostawy, null=True, db_column='iddostawy', blank=True)
    data_transakcji = models.DateField(null=True, blank=True)
    class Meta:
		verbose_name='Ksiegowosc'
		db_table = u'ksiegowosc'
		verbose_name_plural = 'Ksiegowosc'
		ordering = ('idtransakcji',)

sklep/templates/sklep/finalizacja.html
{% extends "base.html" %}
{% load i18n %}
{% load kategorie_sidebar %}

{% block main_box %}
<h2>{% trans "Dziękujemy za dokonanie zakupów w naszym sklepie" %}</h2>

<p>{% trans "Prosimu o dokonanie płatności." %}</p>
<p>{% trans "Na Twój adres e-mail została wysłana wiadomość z instrukcją postępowania." %}</p>

{% endblock %}

{% block side_box %}
<div id="sidebox">
    <h3><center>{% trans "Kategorie" %}</center></h3>
    {% kategorie_sidebar %}
</div>
{% endblock %}

sklep/templates/sklep/glowna.html

{% extends "base.html" %}
{% load i18n %}
{% load kategorie_sidebar %}

{% block main_box %}
<h2>{% trans "Witaj na stronie głównej" %}</h2>

<p>{% trans "System e-commerce wspierający sprzedaż artykułów biurowych"%}</p>
<p>{% trans "Projekt realizowany w ramach przedmiotu ''Zespołowe przedsięwzięcie inżynierskie''" %}</p>
<p>{% trans "Autorzy:" %}</p>
<ul>
<li>Dagmara Gaweł</li>
<li>Łukasz Gąbka</li>
<li>Sławomir Grabiński</li>
<li>Dawid Iwanicki</li>
</ul>
<hr>
<h2>{% trans "Zapraszamy do zapoznania się z ofertą naszego sklepu." %}</h2><br>

{% endblock %}
{% block side_box %}
<div id="sidebox">
    <h3><center>{% trans "Kategorie" %}</center></h3>
    {% kategorie_sidebar %}
</div>
{% endblock %}

sklep/templates/sklep/index.html
<head>

</head>

{% extends "base.html" %}
{% load i18n %}
{% load kategorie_sidebar %}
{% load url from future %}
{% block side_box %}
<div id="sidebox">
    <h3><center>{% trans "Kategorie" %}</center></h3>
    {% kategorie_sidebar %}
</div>
{% endblock %}
{% block main_box %}
<form><input type="text" name="ilosc-1[1]" id="ilosc-1[1]" value="3,00" readonly="readonly"/></form>
{% if form.errors %}
<p class="error">{% trans "Niepoprawne dane lub hasło" %}</p>
{% endif %}

    <h1>{% trans "Dodaj stanowisko" %}</h1>



    <form action="." name="stanowiska" method="post" >
    {% csrf_token %}

        <label>
            <div>{% trans "identyfikator" %}</div> <input type="text" name="identyfikator" id="identyfikator" value="{{identyfikator}}">
        </label>
        <label>
            <div>{% trans "stanowisko" %}</div> <input type="text" name="stanowisko" id="stanowisko" value="{{stanowisko}}">
        </label>

        <div class="error">{{error}}</div>
        <input type="submit" value='{% trans "Wyślij"%}'>
		<input type="hidden" name="next" value="{{ next }}" />
    </form>


{% endblock %}

sklep/templates/sklep/klienci.html
<head>

</head>

{% extends "base.html" %}
{% load i18n %}
{% load kategorie_sidebar %}
{% load url from future %}
{% block side_box %}
<div id="sidebox">
    <h3><center>{% trans "Kategorie" %}</center></h3>
    {% kategorie_sidebar %}
</div>
{% endblock %}
{% block main_box %}

<!--{% if form.errors %}
<p class="error">Niepoprawne dane lub hasło</p>
{% endif %}-->

    <h1>{% trans "Twój profil" %}</h1>

<form><input type="hidden" name="ilosc-1[1]" id="ilosc-1[1]" value="3,00" readonly="readonly"/></form>

    <form action="." name="klienci" method="post" >{% csrf_token %}
	{{ form.non_field_errors }}
	<table>
		<tr>
			<td>{{ form.nik.label_tag.as_hidden }}</td>
			<td>{{ form.nik.as_hidden }}</td>
			<td>{{ form.nik.errors.as_hidden }}</td>
		</tr>
		<tr>
			<td>{{ form.nip.label_tag }}</td>
			<td>{{ form.nip }}</td>
			<td>{{ form.nip.errors }}</td>
		</tr>
		<tr>
			<td><label id="nazwa_firmy" for="id_nazwa_firmy">{% trans "Nazwa firmy"%}</label></td>
			<td>{{ form.nazwa_firmy }}</td>
			<td>{{ form.nazwa_firmy.errors }}</td>
		</tr>
		<tr>
			<td><label id="nazwisko" for="id_nazwisko">{% trans "Nazwisko"%}</label></td>
			<td>{{ form.nazwisko }}</td>
			<td>{{ form.nazwisko.errors }}</td>
		</tr>
		<tr>
			<td><label id="imie" for="id_imie">{% trans "Imię"%}</label></td>
			<td>{{ form.imie }}</td>
			<td>{{ form.imie.errors }}</td>
		</tr>
		<tr>
			<td><label id="miasto" for="id_miasto">{% trans "Miasto"%}</label></td>
			<td>{{ form.miasto }}</td>
			<td>{{ form.miasto.errors }}</td>
		</tr>
		<tr>
			<td><label id="ulica" for="id_ulica">{% trans "Ulica"%}</label></td>
			<td>{{ form.ulica }}</td>
			<td>{{ form.ulica.errors }}</td>
		</tr>
		<tr>
			<td><label id="numer" for="id_numer">{% trans "Numer"%}</label></td>
			<td>{{ form.numer }}</td>
			<td>{{ form.numer.errors }}</td>
		</tr>
		<tr>
			<td><label id="kod_pocztowy" for="id_kod_pocztowy">{% trans "Kod pocztowy"%}</label></td>
			<td>{{ form.kod_pocztowy }}</td>
			<td>{{ form.kod_pocztowy.errors }}</td>
		</tr>
		<tr>
			<td><label id="poczta" for="id_poczta">{% trans "Poczta"%}</td>
			<td>{{ form.poczta }}</td>
			<td>{{ form.poczta.errors }}</td>
		</tr>
		<tr>
			<td><label id="telefon" for="id_telefon">{% trans "Telefon"%}</td>
			<td>{{ form.telefon }}</td>
			<td>{{ form.telefon.errors }}</td>
		</tr>
		<tr>
			<td></td>
			<td><input type="hidden" name="login" id="login" value="{{user.pk}}"></td>
			<td>{{ form.login.errors }}</td>
		</tr>
		<tr>
			<td>{{ forms.email.label_tag }}</td>
			<td>{{ forms.email }}</td>
			<td>{{ forms.email.errors }}</td>
		</tr>
	</table>


        <input id="target" type="submit" value='{% trans "Wyślij"%}'>
		<input type="hidden" name="next" value="{{ next }}" />
    </form>

<script>
$("#target").click(function() {
  if ($('#id_nip').val() == ''){
  $("#id_nip").val(" ")}
  if ($('#id_telefon').val() == ''){
  $("#id_telefon").val(" ")}
  
    if (($('#id_nazwa_firmy').is(':hidden'))&&(($('#id_imie').val() != '')&&($('#id_nazwisko').val() != '')))
	{
	   //alert("ukryta nazwa firmy");
		$("#id_nazwa_firmy").val(" ")
	}
	if (($('#id_nazwa_firmy').is(':hidden'))&&(($('#id_imie').val() == '')||($('#id_nazwisko').val() == '')))
	{
	//alert("Nazwa firmy na 2 spacje");
	$("#id_nazwa_firmy").val("  ");
	}
	if ((($('#id_nazwisko').is(':hidden'))||($('#id_imie').is(':hidden')))&&($('#id_nazwa_firmy').val() != ''))
	{
	   //alert("ukryta nazwisko i imie");
		$("#id_nazwisko").val(" ");
		$("#id_imie").val(" ");
	}
	if ((($('#id_nazwisko').is(':hidden'))||($('#id_imie').is(':hidden')))&&($('#id_nazwa_firmy').val() == ''))
	{
	   //alert("ukryta nazwisko i imie na 2 spacje");
		$("#id_nazwisko").val("  ");
		$("#id_imie").val("  ");
	}
  
  
  
  
});

</script>
<script>
$(document).ready(function() {


if (($('#id_nazwa_firmy').val() == '')){
            $("#id_nazwa_firmy").hide();
			$("#nazwa_firmy").hide();
			$("#id_nazwisko").show();
			$("#imie").show();
			$("#nazwisko").show();
			$("#id_imie").show();
}
if (($('#id_nazwisko').val() == '')||($('#id_imie').val() == '')){
            $("#id_nazwisko").hide();
			$("#imie").hide();
			$("#nazwisko").hide();
			$("#id_imie").hide();
			$("#id_nazwa_firmy").show();
			$("#nazwa_firmy").show();
}
if (($('#id_nazwa_firmy').val() == ' ')){
            $("#id_nazwa_firmy").hide();
			$("#nazwa_firmy").hide();
			$("#id_nazwisko").show();
			$("#imie").show();
			$("#nazwisko").show();
			$("#id_imie").show();
}
if (($('#id_nazwisko').val() == ' ')||($('#id_imie').val() == ' ')){
            $("#id_nazwisko").hide();
			$("#imie").hide();
			$("#nazwisko").hide();
			$("#id_imie").hide();
			$("#id_nazwa_firmy").show();
			$("#nazwa_firmy").show();
}
if (($('#id_nazwa_firmy').val() == '  ')){
            $("#id_nazwa_firmy").hide();
			$("#nazwa_firmy").hide();
			$("#id_nazwisko").show();
			$("#imie").show();
			$("#nazwisko").show();
			$("#id_imie").show();
}
if (($('#id_nazwisko').val() == '  ')||($('#id_imie').val() == '  ')){
            $("#id_nazwisko").hide();
			$("#imie").hide();
			$("#nazwisko").hide();
			$("#id_imie").hide();
			$("#id_nazwa_firmy").show();
			$("#nazwa_firmy").show();
}












//$('#id_nik').attr("disabled",true); 
if ($('#id_nip').val() != " "){
    var wartosc = $("#id_nip").val();
    index1 = wartosc.substr(0, 1);
    index2 =  parseInt(wartosc.substr(1));
    if (index1 == " "){
		$("#id_nip").val(index2)
    }
    else{
		$("#id_nip").val(wartosc)
   }
}
else{
$("#id_nip").val("")
}

if ($('#id_telefon').val() != " "){
    var wartosc = $("#id_telefon").val();
    index1 = wartosc.substr(0, 1);
    index2 =  parseInt(wartosc.substr(1));
    if (index1 == " "){
		$("#id_telefon").val(index2)
    }
    else{
		$("#id_telefon").val(wartosc)
   }
}
else{
$("#id_telefon").val("")
}

});
</script>
{% endblock %}

sklep/templates/sklep/kontakt.html
{% extends "base.html" %}
{% load i18n %}
{% load kategorie_sidebar %}

{% block main_box %}
<h2>{% trans "Kontakt" %}</h2>
<p>{% trans "Dane firmy: ZPI 2012 Sp. z o.o." %}</p>
<p>{% trans "Adres: Wrocław, ul. Politechnicka 1" %}</p>
<p>{% trans "Telefon: (11) 111-11-11" %}</p>
<p>{% trans "nr konta: PL 11 1111 1111 1111 1111 1111 1111" %}</p>
<p>{% trans "Adres e-mail: cytrynowypatrol@gmail.com" %}</p>

{% endblock %}

{% block side_box %}
<div id="sidebox">
    <h3><center>{% trans "Kategorie" %}</center></h3>
    {% kategorie_sidebar %}
</div>
{% endblock %}

sklep/templates/sklep/opiszamowienia.html
<head>

</head>

{% extends "base.html" %}
{% load i18n %}
{% load kategorie_sidebar %}
{% load url from future %}
{% block side_box %}
<div id="sidebox">
    <h3><center>{% trans "Kategorie" %}</center></h3>
    {% kategorie_sidebar %}
</div>
{% endblock %}
{% block main_box %}

<!--{% if form.errors %}
<p class="error">Niepoprawne dane lub hasło</p>
{% endif %}-->

    <h1>{% trans "Opis" %}</h1>

<form><input type="hidden" name="ilosc-1[1]" id="ilosc-1[1]" value="3,00" readonly="readonly"/></form>

    <form action="." name="zamowienia" method="post" >{% csrf_token %}
	{{ forms.non_field_errors }}
	<table>
		<tr>
			<td><label id="idzamowienia1" for="id_idzamowienia1">{% trans "Zamówienie"%}</label></td>
			<td>{{ forms.idzamowienia1 }}</td>
			<td>{{ forms.idzamowienia1.errors }}</td>
		</tr>
		<tr>
			<td><label id="idtowaru" for="id_idtowaru">{% trans "Towar"%}</label></td>
			<td>{{ forms.idtowaru }}</td>
			<td>{{ forms.idtowaru.errors }}</td>
		</tr>
		<tr>
			<td><label id="ilosc" for="id_ilosc">{% trans "Ilość"%}</label></td>
			<td>{{ forms.ilosc }}</td>
			<td>{{ forms.ilosc.errors }}</td>
		</tr>
	</table>


        <input type="submit" value='{% trans "Wyślij"%}'>
		<input type="hidden" name="next" value="{{ next }}" />
    </form>


{% endblock %}